version: '3.1'
services:
# https://www.elastic.co/guide/en/kibana/current/docker.html
# https://www.elastic.co/guide/en/elasticsearch/reference/8.0/docker.html
# VM 内存要求比较大
# echo vm.max_map_count=262144 >> /etc/sysctl.conf 
# 重载 sysctl -p
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9300:9200
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9400:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: "kibana"
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9300","http://es03:9400"]'
    depends_on:
      - es01
      - es02
      - es03
