version: "3.1"
services: 

  mongo:
    container_name: 'mongo'
    image: mongo
    restart: always
    ports:
      - "27017:27017"
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yuanmoc
