version: '2'
services:
  rmqnamesrv:
    image: apacherocketmq/rocketmq:latest
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./file/rmqnamesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
  rmqbroker:
    image: apacherocketmq/rocketmq:latest
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./file/rmqbroker/logs:/home/rocketmq/logs
      - ./file/rmqbroker/store:/home/rocketmq/store
      - ./env/broker.conf:/home/rocketmq/conf/broker.conf
    environment:
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: sh mqbroker -n rmqnamesrv:9876 -c /home/rocketmq/conf/broker.conf
    depends_on:
      - rmqnamesrv
  rmqconsole:
    image: styletang/rocketmq-console-ng:latest
    container_name: rmqconsole
    ports:
      - 8081:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
